### ISSUE TITLE
Change the "Download PDF" range !!

### ISSUE THREAD

**Issue by u100009** [MicrosoftDocs/msftdynamicsgpdocs#187]
Please Microsoft change the way that downloading the documentation selects the  pages.. currently it just takes everything under the main title, which means you end up with a document of well over 2800 pages, which is completely unusable. 
Dynamics GP documentation used to be available as individual PDF files per module and this should remain like this, even now that the documentation is managed online. 
Thanks for considering this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393a7f9b-3756-544c-1dfd-f6f1fd5bcf2e
* Version Independent ID: c663b3d3-6770-8bcf-804e-74990a9a428f
* Content: [Canadian Payroll 2019 Year-end Update & 2020 Tax Update - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/payroll/can18yetax#feedback)
* Content Source: [dynamics-gp/payroll/CAN18YETax.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/payroll/CAN18YETax.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by edupont04** [comment]
Hello u100009,
Thank you for your feedback! We have moved the Dynamics GP content to the Docs.microsoft.com so that it is more discoverable and easy to collaborate on. Because we can now update individual pages, a downloaded PDF can quickly become outdated.
The Download PDF button does indeed generate a PDF file with everything. This is not something we can change very easily, but we will take your input into consideration - you can also choose to submit a feature request for the Docs.microsoft.com site here: [https://aka.ms/sitefeedback](https://aka.ms/sitefeedback)

**Comment by u100009** [comment]
Thank you Eva,
I did a research in the site feedback link you provided and found several other posts with similar problems reported. I've added my comments on those existing ones, so as to emphasize the issue. I've seen that some of the reported issues have been flagged as bugs and were assigned to some MS teams. I'm going to keep an eye on this.
