### ISSUE TITLE
Pictures missing from the Dynamics GP docs pages

### ISSUE THREAD

**Issue by u100009** [MicrosoftDocs/msftdynamicsgpdocs#248]
Since Microsoft stopped updating the PDF versions of the Dynamics GP product way back in GP2013, we're forced to use the online 'Docs' pages to keep user documentation handy.. 
However, the more I dig & read thru it, the more I feel it's neglected and there is little QA control, as I see lots of doc pages that should have pictures (like the good ol' PDF's) and there is only a placeholder for it.. 
![IAMGE](media/PACM 2.jpg)
PACM 4.JPEG
![A screenshot ](media/051e992556a8e343d2f4096c675d8d78.jpg)

One example is the Project Accounting CM section : 
https://docs.microsoft.com/en-us/dynamics-gp/distribution/projacctcostmanagement

It is not generalized, but it happens way too often that I can't really tell my clients to refer back to this documentation for user training in GP. 
Please have someone read-proof the pages and update them more frequently. 
Also, PLEASE, allow for download a section in PDF without having to print 3000 pages (basically the entire Dynamics GP documentation).  
Thank you!
@GP_Beat

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com is migrated bit by bit from the original manuals. You are right that there are many migration errors, including broken links, metadata showing rather than being hidden, wrong links to images, and so on. A good example is the image that you point to - it's showing metadata that is supposed to be accessed by screen readers only due to an error in the migration tool.

We are painfully aware of these issues and fix them bit by bit as resources allows. Specifically your ask to get more granular downloadable PDFs, this is something that we hope will become available later this year.
