### ISSUE TITLE
Missing images and links - documentation broken.

### ISSUE THREAD

**Issue by lordyoda** [MicrosoftDocs/msftdynamicsgpdocs#284]
The images are not visible.. seems like broken links.
Additionally, there seem to be links to pages that are broken as well.
There are text entries on the page that read "See Distributed Process Server" for example.
I believe that is meant to be a link as it is also italicized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffc33a7-017e-7bb9-e8bf-7124f8e70ec4
* Version Independent ID: 4d1841ca-fbf4-d52a-dda4-0b67045ec6ab
* Content: [System Administration Guide  - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/installation/systemadminguide#checking-links)
* Content Source: [dynamics-gp/installation/SystemAdminGuide.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/installation/SystemAdminGuide.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com is migrated bit by bit from the original manuals. You are right that there are many migration errors, including broken links,  metadata showing rather than being hidden, wrong links to images, and so on. A good example is the sentence "See Distributed Process Server" that you point to - in the original manual, it was a bookmark to another section. On the Docs.microsoft.com site, it's supposed to be a hyperlink, but that didn't get caught in by the migration tool, and so it just renders as text.

We are painfully aware of these issues and fix them bit by bit as resources allows.
